### ISSUE TITLE
Issues with Solver004

### ISSUE THREAD

**Issue by 3pcomps** [oseresta/3pcomps#1]
1. typo mistake in solver004.py 

return self._MT and MC - corrected

2. changed formats in solverIO.py

Modified files are uploaded in google drive

**Comment by 3pcomps** [comment]
If (ILoad = 0) Then ZUP(1) = -TOTTHK / 2   ' Reference Plane @ Mid
     If (ILoad = 1) Then ZUP(1) = -TOTTHK       ' Reference Plane @ Lower
     If (ILoad = 2) Then ZUP(1) = 0#            ' Reference Plane @ Upper
     If (ILoad > 2) Then ZUP(1) = Offs        'Reference Plane @ actual offset
For k = 1 To Nply
            If (k > 1) Then ZUP(k) = ZLO(k - 1) ' Note that the Upper & Lower are switched from shown convention, ie upper is ply 1
            ZLO(k) = ZUP(k) + THK(k) ' Note that the Upper & Lower are switched
     Next k

**Comment by oseresta** [comment]
1. Fixed typo
2. Implemented offsets
3. Updated output
